void launch_applyAttn(float* output,
                      const float* attnMap,
                      const float* v,
                      int B,
                      int Heads,
                      int winh,
                      int winw,
                      int C,
                      int H,
                      int W);