void launch_rendering(float* image,
                      const float* direction,
                      const float* origin,
                      const float* tsdf,
                      int B,
                      int H,
                      int W,
                      int vH,
                      int vW,
                      int times,
                      float voxel_size,
                      float xmin,
                      float xmax,
                      float ymin,
                      float ymax,
                      float zmin,
                      float zmax);